#!/usr/bin/env bash
MODULE=${1:-opnsense_cli}
MIN_COVERAGE=${2:-100}
if [ -n "$1" ]; then
  MODULE=$(printf ' %q' "$@")
fi

pytest --exitfirst --verbose --failed-first --cov=${MODULE} --cov-report term-missing --cov-fail-under=${MIN_COVERAGE} ${MODULE} --verbosity=5
