#!/bin/bash
pip install -e .
cp -rv ~/.opn-cli ~/.opn-cli.bak
mkdir -p ~/.opn-cli
cp opnsense_cli/ca.pem ~/.opn-cli/.
cp opnsense_cli/conf.yaml ~/.opn-cli/.
vagrant up

# install required opnsense plugins
opn-cli plugin install os-firewall
