#!/bin/bash
# install test dependencies
pip3 install -r test_requirements.txt

# install editable
pip3 install -e .

# deploy configuration
cp -rv ~/.opn-cli ~/.opn-cli.bak
mkdir -p ~/.opn-cli
cp opnsense_cli/ca.pem ~/.opn-cli/.
cp opnsense_cli/conf.yaml ~/.opn-cli/.

# setup test device
vagrant up

# install required opnsense plugins
opn-cli plugin install os-firewall
opn-cli plugin install os-haproxy

echo "OPNSense URL:"
echo "https://127.0.0.1:10443/"
echo "Login: root"
echo "Pass: opnsense"
echo
