#!/usr/bin/env bash
while getopts "fh" arg; do
  # shellcheck disable=SC2220
  case $arg in
    f)
      ruff check --fix --statistics
      ;;
    h)
      echo "Usage: $0 [-f] [-h]"
      echo "  -f: auto fix lint issues"
      echo "  -h: help"
      exit 0
      ;;
  esac
done

ruff check --output-format=full
