#!/usr/bin/env bash
while getopts "fh" arg; do
  # shellcheck disable=SC2220
  case $arg in
    f)
      ruff check --fix --extend-exclude './venv,./output, ./build' --statistics --extend-ignore=E203 --line-length=127
      ;;
    h)
      echo "Usage: $0 [-f] [-h]"
      echo "  -f: auto fix lint issues"
      echo "  -h: help"
      exit 0
      ;;
  esac
done

ruff check --extend-exclude './venv,./output, ./build' --output-format=full --extend-ignore=E203 --line-length=127
