#!/usr/bin/env bash
ARGS="."
if [ -n "$1" ]; then
  ARGS=$(printf ' %q' "$@")

fi
pytest --exitfirst --verbose --failed-first --cov opnsense_cli --cov-config .coveragerc ${ARGS}
#pytest --ignore=./output --verbose ${ARGS}
